# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atlas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.state = None
        self.output = None
        self.pushButton_2 = None
        self.pushButton = None
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.verticalLayout_3 = None
        self.frame_body = None
        self.bye = None
        self.max = None
        self.min = None
        self.hide = None
        self.Tittle = None
        self.cont_tittle = None
        self.horizontalLayout = None
        self.frame_top = None
        self.verticalLayout_2 = None
        self.main_body = None
        self.verticalLayout = None
        self.wg_central = None

    def setupUi(self, _MainWindow):
        _MainWindow.setObjectName("MainWindow")
        _MainWindow.resize(400, 250)
        _MainWindow.setMinimumSize(QtCore.QSize(400, 250))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        _MainWindow.setFont(font)
        _MainWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        _MainWindow.setWindowIcon(icon)
        _MainWindow.setStyleSheet("*{\n"
                                  "    backgrond-color: transparent;\n"
                                  "}\n"
                                  "#wg_central{\n"
                                  "    background-color: #00183D;\n"
                                  "}\n"
                                  "#main_body{\n"
                                  "    background-color: #00327D;\n"
                                  "    border-radius: 10px;\n"
                                  "}\n"
                                  "/*//////////////////////////////*/\n"
                                  "QPushButton:disabled{\n"
                                  "    background-color: #838383;\n"
                                  " }\n"
                                  "QPushButton{\n"
                                  "    padding: 10px;\n"
                                  "    background-color: rgb(234, 239, 238);\n"
                                  "    color: rgb(0, 0, 0);\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "    background-color: #B7BDBB;\n"
                                  "}\n"
                                  "QPushButton:pressed{\n"
                                  "    background-color: #FFF;\n"
                                  "}")
        self.wg_central = QtWidgets.QWidget(_MainWindow)
        self.wg_central.setStyleSheet("")
        self.wg_central.setObjectName("wg_central")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wg_central)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_body = QtWidgets.QFrame(self.wg_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setFrameShape(QtWidgets.QFrame.Box)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Plain)
        self.main_body.setObjectName("main_body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.main_body)
        self.frame_top.setMidLineWidth(5)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cont_tittle = QtWidgets.QVBoxLayout()
        self.cont_tittle.setContentsMargins(-1, -1, -1, 5)
        self.cont_tittle.setObjectName("cont_tittle")
        self.Tittle = QtWidgets.QLabel(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Tittle.setFont(font)
        self.Tittle.setStyleSheet("border-radius: 5px;\n"
                                  "background-color: rgb(234, 239, 238);\n"
                                  "color: rgb(0, 44, 109);")
        self.Tittle.setObjectName("Tittle")
        self.cont_tittle.addWidget(self.Tittle)
        self.horizontalLayout.addLayout(self.cont_tittle)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.hide = QtWidgets.QPushButton(self.frame_top)
        self.hide.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setBold(True)
        font.setWeight(75)
        self.hide.setFont(font)
        self.hide.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hide.setStyleSheet("Border: None;\n"
                                "border-top-left-radius: 5px;\n"
                                "color: rgb(0, 44, 109);")
        self.hide.setIconSize(QtCore.QSize(20, 20))
        self.hide.setObjectName("hide")
        self.horizontalLayout.addWidget(self.hide)
        self.min = QtWidgets.QPushButton(self.frame_top)
        self.min.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setBold(True)
        font.setWeight(75)
        self.min.setFont(font)
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setStyleSheet("border: None;\n"
                               "color: rgb(0, 44, 109);")
        self.min.setIconSize(QtCore.QSize(20, 20))
        self.min.setObjectName("min")
        self.horizontalLayout.addWidget(self.min)
        self.max = QtWidgets.QPushButton(self.frame_top)
        self.max.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setBold(True)
        font.setWeight(75)
        self.max.setFont(font)
        self.max.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.max.setStyleSheet("border: None;\n"
                               "color: rgb(0, 44, 109);")
        self.max.setIconSize(QtCore.QSize(20, 20))
        self.max.setObjectName("max")
        self.horizontalLayout.addWidget(self.max)
        self.bye = QtWidgets.QPushButton(self.frame_top)
        self.bye.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setBold(True)
        font.setWeight(75)
        self.bye.setFont(font)
        self.bye.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bye.setStyleSheet("Border: None;\n"
                               "border-top-right-radius: 5px;\n"
                               "color: rgb(0, 44, 109);")
        self.bye.setIconSize(QtCore.QSize(20, 20))
        self.bye.setObjectName("bye")
        self.horizontalLayout.addWidget(self.bye)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_body = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_body.sizePolicy().hasHeightForWidth())
        self.frame_body.setSizePolicy(sizePolicy)
        self.frame_body.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_body.setStyleSheet("background-color: rgb(234, 239, 238);\n"
                                      "border-top-left-radius: 5px;")
        self.frame_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_body.setObjectName("frame_body")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_body)
        self.verticalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 5px;\n"
                                      "background-color: rgb(0, 44, 109);\n"
                                      "color: rgb(255, 255, 255);")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-radius: 5px;\n"
                                        "background-color: rgb(0, 44, 109);\n"
                                        "color: rgb(255, 255, 255);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.state = QtWidgets.QLabel(self.frame_body)
        self.state.setMinimumSize(QtCore.QSize(0, 31))
        self.state.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.state.setFont(font)
        self.state.setStyleSheet("border-radius: 5px;\n"
                                 "background-color: rgb(0, 44, 109);\n"
                                 "color: rgb(255, 255, 255);")
        self.state.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.state.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.horizontalLayout_2.addWidget(self.state)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.output = QtWidgets.QTextBrowser(self.frame_body)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setStyleSheet("color: rgb(255, 255, 255);\n"
                                  "background-color: rgb(0, 24, 61);\n"
                                  "border-radius: 5px;")
        self.output.setObjectName("output")
        self.verticalLayout_3.addWidget(self.output)
        self.verticalLayout_2.addWidget(self.frame_body)
        self.verticalLayout.addWidget(self.main_body)
        _MainWindow.setCentralWidget(self.wg_central)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(_MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Tittle.setText(_translate("MainWindow", "  BLUE BOY  "))
        self.hide.setText(_translate("MainWindow", "hide"))
        self.min.setText(_translate("MainWindow", "min"))
        self.max.setText(_translate("MainWindow", "max"))
        self.bye.setText(_translate("MainWindow", "bye"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.state.setText(_translate("MainWindow", "Txt"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
